[package]
name = "cyclist"
version = "0.1.0"
edition = "2021"

[features]
default = ["std", "keccyak", "xoodyak"]
std = ["subtle/std", "zeroize/std"]
keccyak = ["keccak-p"]
xoodyak = ["xoodoo-p"]

[dependencies]
byteorder = "1.4.3"
keccak-p = { version = "0.1.0", optional = true }
subtle = "2.4.1"
xoodoo-p = { version = "0.1.0", optional = true }
zeroize = "1.5.5"

[dev-dependencies]
aead = "0.4.3"
aes-gcm = "0.9.4"
chacha20poly1305 = "0.10.0-pre"
criterion = { version = "0.3.5", features = ["html_reports"] }
sha2 = "0.10.2"
sha3 = "0.10.1"
strobe-rs = "0.7.1"

[[bench]]
name = "benchmarks"
harness = false
